### ISSUE TITLE
[suggestion] When using an unbreakable knife, it won't lose durability when using the cutting board.

### ISSUE THREAD

**Issue by noawx** [jahirxtrap/foodtxf#1]
When you add the "Unbreakable" tag to a knife, you can swing it without losing durability, like any other tool.

But when you use an Unbreakable knife in a recipe, it loses the Unbreakable tag and loses durability.

Would be cool if it didn't use the durability of an unbreakable knife.

**Comment by jahirxtrap** [comment]
Added in v1.6.0

**Comment by noawx** [comment]
Thanks
![image](https://github.com/jahirxtrap/foodtxf/assets/76262280/3a6a6d40-1c2e-40c8-8ec9-53b7b17f0aa6)
