### ISSUE TITLE
I can't put the mod in my server

### ISSUE THREAD

**Issue by IsaelcuevasMendez** [jahirxtrap/foodtxf#3]
When i try to put the mod the console show me a message saying "Failed to create mod instance. ModID: foodtxf, class com.jahirtrap.foodtxf.FoodtxfMod" 
who can help me?

**Comment by jahirxtrap** [comment]
In which version and mod loader does it occur?

**Comment by IsaelcuevasMendez** [comment]
In version 1.21, is in a server

**Comment by jahirxtrap** [comment]
This is an error that only occurs with Forge. I'll check it when I have time.

**Comment by IsaelcuevasMendez** [comment]
thanks, Will you tell me when the update is available

**Comment by jahirxtrap** [comment]
Fixed in 1.6.6
